library:
  source-dirs: src
  default-extensions:
    - NoImplicitPrelude
    - OverloadedStrings
tests:
  AdventOfCode18-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode18
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- text
- base >= 4.7 && < 5
- parser-combinators
- relude
- megaparsec
- containers
- optparse-applicative
- pretty-terminal

name: AdventOfCode18
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/AdventOfCode18
license: BSD3
executables:
  AdventOfCode18-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode18
    default-extensions:
    - NoImplicitPrelude
    - OverloadedStrings
description: Please see the README on GitHub at <https://github.com/githubuser/AdventOfCode18#readme>
